/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package view.admin;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import view.user.*;

/**
 *
 * @author isaac
 */
public class DetalhesNotificacaoViewAdmin extends javax.swing.JInternalFrame {

    /**
     * Creates new form DetalhesNotificacaoViewUser
     */
    public DetalhesNotificacaoViewAdmin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        lblRemetente = new javax.swing.JLabel();
        txtRemetente = new javax.swing.JTextField();
        lblMensagem = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAreaMensagem = new javax.swing.JTextArea();
        btnFechar = new javax.swing.JButton();
        btnRecusar = new javax.swing.JButton();
        btnAceitar = new javax.swing.JButton();
        lblData = new javax.swing.JLabel();
        txtData = new javax.swing.JTextField();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        setTitle("Detalhes");

        lblRemetente.setText("Remetente");

        txtRemetente.setEditable(false);

        lblMensagem.setText("Mensagem");

        txtAreaMensagem.setEditable(false);
        txtAreaMensagem.setColumns(20);
        txtAreaMensagem.setRows(5);
        jScrollPane2.setViewportView(txtAreaMensagem);

        btnFechar.setText("Fechar");

        btnRecusar.setText("Recusar");

        btnAceitar.setText("Aceitar");

        lblData.setText("Data");

        txtData.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblMensagem)
                        .addContainerGap(495, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane2)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnAceitar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnRecusar)
                                .addGap(12, 12, 12)
                                .addComponent(btnFechar))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblRemetente)
                                    .addComponent(lblData))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtData)
                                    .addComponent(txtRemetente))))
                        .addGap(37, 37, 37))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRemetente)
                    .addComponent(txtRemetente, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblData)
                    .addComponent(txtData, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(lblMensagem)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFechar)
                    .addComponent(btnRecusar)
                    .addComponent(btnAceitar))
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceitar;
    private javax.swing.JButton btnFechar;
    private javax.swing.JButton btnRecusar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lblData;
    private javax.swing.JLabel lblMensagem;
    private javax.swing.JLabel lblRemetente;
    private javax.swing.JTextArea txtAreaMensagem;
    private javax.swing.JTextField txtData;
    private javax.swing.JTextField txtRemetente;
    // End of variables declaration//GEN-END:variables

    public JButton getBtnAceitar() {
        return btnAceitar;
    }

    public JButton getBtnFechar() {
        return btnFechar;
    }

    public JButton getBtnRecusar() {
        return btnRecusar;
    }

    public JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    public JScrollPane getjScrollPane2() {
        return jScrollPane2;
    }

    public JTextArea getjTextArea1() {
        return jTextArea1;
    }

    public JLabel getLblRemetente() {
        return lblRemetente;
    }

    public JTextArea getTxtAreaMensagem() {
        return txtAreaMensagem;
    }

    public JTextField getTxtRemetente() {
        return txtRemetente;
    }

    public JLabel getTxtRemetente1() {
        return lblMensagem;
    }

    public JLabel getLblMensagem() {
        return lblMensagem;
    }

    public JLabel getLblData() {
        return lblData;
    }

    public JTextField getTxtData() {
        return txtData;
    }

    
    
}
